# Autogenerated template loader (source)
# This mirrors the dist loader. Edit individual files in Classes/, Private/, Public/

# Classes
if (Test-Path "$PSScriptRoot\Classes") { Get-ChildItem -LiteralPath "$PSScriptRoot\Classes" -Filter *.ps1 -Recurse -ErrorAction SilentlyContinue | ForEach-Object { . $_.FullName } }

# Private
if (Test-Path "$PSScriptRoot\Private") { Get-ChildItem -LiteralPath "$PSScriptRoot\Private" -Filter *.ps1 -Recurse -ErrorAction SilentlyContinue | ForEach-Object { . $_.FullName } }

# Public
if (Test-Path "$PSScriptRoot\Public") {
    Get-ChildItem -LiteralPath "$PSScriptRoot\Public" -Filter *.ps1 -Recurse -ErrorAction SilentlyContinue |
        ForEach-Object { . $_.FullName }
}

# Exports are handled by Export-ModuleMember calls executed at import time in dist,
# or left empty here to allow Test-ModuleManifest to succeed quickly.
